name: Enterprise Apache CI/CD


on:
  push:
    branches:
      - main
      - development
      - 'feature/**'


permissions:
  contents: read
  packages: write


jobs:
  docker:
    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract Docker Matadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/enterpriseplateform



      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./apache
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
