name: Git-Labs CI


on:
  push:
    branches:
      - main
      - development
      - feature/*
      - hotfix/*


pull_request:


jobs:
  basic-check:


    runs-on: ubuntu-latest


    steps:


      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Show Current Directory
        run: pwd


      - name: List Repository Files
        run: ls -la


      - name: Display Git Status
        run: git status


      - name: Display Current Branch
        run: git branch


      - name: Print Success Message
        run: echo "Enterprise Git-Labs CI executed successfully."
